name: Continuous Integration & Deployment

on: 
  push:
    paths-ignore:
      - "**.md"
      - "documentation/**"
  pull_request: 
    paths-ignore:
      - "**.md"
      - "documentation/**"
  schedule:
    - cron: "0 22 * * 5" #At 10PM every Friday

jobs:
  build:
    name: Provision the test container and run the tests
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo content 
      uses: actions/checkout@v2

    - name: Create .env file # docker-compose looks for .env file even though it is not required to spin up the test container
      run: |
        touch .env

    - name: Spin up test container and run the tests 
      run: docker-compose up webapp-test

    - name: Send Notification on Slack
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }}
        notification_title: '{workflow} has {status_message}'
        message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
        footer: 'Linked Repo <{repo_url}|{repo}>'
        mention_users: 'U03GZQ5GCQ0'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  publish:
    name: Login to DockerHub, build an image and publish it
    runs-on: ubuntu-latest
    needs: build
    if: ${{github.event_name == 'push' && github.ref == 'refs/heads/main'}}
    steps:

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache Docker layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/to-do-app:latest,${{ secrets.DOCKERHUB_USERNAME }}/to-do-app:${{ github.sha }}

  provision_infrastructure:
    name: Spin up / Reconfigure the infrastructure.
    runs-on: ubuntu-latest
    needs: publish
    if: ${{github.event_name == 'push' && github.ref == 'refs/heads/main'}}
    steps:

      - name: Checkout repo content 
        uses: actions/checkout@v2

      - name: Terraform init
        run: |
          cd infrastructure/
          terraform init
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Terraform apply
        run: |
          cd infrastructure/
          terraform apply --auto-approve
        env:
          TF_VAR_oauth_client_id: ${{ secrets.OAUTH_CLIENT_ID }}
          TF_VAR_oauth_client_secret: ${{ secrets.OAUTH_CLIENT_SECRET }}
          TF_VAR_admin_id: ${{ secrets.ADMIN_ID }}
          TF_VAR_prefix: ${{ secrets.PREFIX }}
          TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
          TF_VAR_flask_env: ${{ secrets.FLASK_ENV }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Deploy the latest version of the image
        run: |
          cd infrastructure/
          curl -dH -X POST "$(terraform output -raw webhook)"
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}