name: Continuous Integration

on: 
  push:
  schedule:
    - cron: "0 22 * * 5" #At 10PM every Friday

jobs:
  build:
    name: Provision the test container and run the tests
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo content 
      uses: actions/checkout@v2

    - name: Read .env file from encoded .env.txt file
      env:
        ENCODED_ENV_FILE: ${{secrets.ENV_FILE}}
      run: echo $ $ENCODED_ENV_FILE | base64 --decode > .env

    - name: Spin up test container and run the tests 
      run: docker-compose up webapp-test